[build]
  # OVO JE PODEŠAVANJE PRESUDNO:
  # 'dist/frontend' je tvoja tačna izlazna putanja
  publish = "dist/frontend" 
  
  # Ova komanda mora da sadrži --base-href / (koje si već dodao u package.json)
  command = "npm run build" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200